# Generated by Django 4.0.5 on 2022-07-21 04:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('detail_image2', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('detail_image3', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('detail_image4', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('detail_image5', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('detail_image6', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('title', models.CharField(max_length=250, verbose_name='Basliq')),
                ('descrtiption_block', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun blok')),
                ('descrtiption', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('descrtiption2', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('descrtiption3', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('descrtiption4', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('descrtiption5', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('descrtiption6', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil')),
                ('time', models.PositiveIntegerField(default=0, verbose_name='Neçə dəqiqəlik xəbər')),
                ('video_link', models.URLField(blank=True, max_length=300, null=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.userprofile')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newstags')),
            ],
        ),
    ]
