# Generated by Django 4.0.4 on 2022-06-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='Neçə dəqiqəlik xəbər'),
        ),
    ]
