# Generated by Django 4.0.5 on 2022-06-30 22:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descrtiption2',
            field=tinymce.models.HTMLField(default=1, max_length=5000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='descrtiption3',
            field=tinymce.models.HTMLField(default=1, max_length=5000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='descrtiption4',
            field=tinymce.models.HTMLField(default=11, max_length=5000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='descrtiption5',
            field=tinymce.models.HTMLField(default=11, max_length=5000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='descrtiption6',
            field=tinymce.models.HTMLField(default=1, max_length=5000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
    ]
