# Generated by Django 4.0.4 on 2022-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='descrtiption',
            field=models.CharField(max_length=5000, verbose_name='Məzmun'),
        ),
    ]
