# Generated by Django 4.0.4 on 2022-06-29 14:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_descrtiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='descrtiption',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='Məzmun'),
        ),
    ]
