# Generated by Django 4.0.5 on 2022-07-01 00:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='descrtiption',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descrtiption2',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descrtiption3',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descrtiption4',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descrtiption5',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descrtiption6',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
    ]
