# Generated by Django 4.0.5 on 2022-07-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Elanın kateqoriyası')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=256, verbose_name='Ad və Soyad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/admin_image', verbose_name='Şekil')),
                ('work', models.CharField(max_length=256, verbose_name='İş')),
                ('linkedin', models.CharField(blank=True, max_length=256, null=True, verbose_name='Linkedin')),
                ('twitter', models.CharField(blank=True, max_length=256, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=256, null=True, verbose_name='Facebook')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/creer_center', verbose_name='Logo')),
                ('descrtiption', tinymce.models.HTMLField(max_length=15000, verbose_name='Məzmun')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq')),
                ('slug', models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('company', models.CharField(max_length=50, verbose_name='Şirkət')),
                ('mail', models.CharField(max_length=50, verbose_name='Mail')),
                ('adress', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.careercentercategory')),
            ],
        ),
    ]
