# Generated by Django 4.0.4 on 2022-05-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Basliq')),
                ('descrtiption', models.CharField(max_length=500, verbose_name='Məzmun')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('views', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images', verbose_name='Şekil')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('mail', models.CharField(max_length=50, verbose_name='Mail')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('message', models.CharField(max_length=256, verbose_name='Mesaj')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.articles')),
            ],
        ),
    ]
