# Generated by Django 4.0.5 on 2022-07-06 14:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercenter',
            name='descrtiption',
            field=tinymce.models.HTMLField(default=1, max_length=15000, verbose_name='Məzmun'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DesiredFeautures',
        ),
    ]
