# Generated by Django 4.0.5 on 2022-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descrtiption',
            field=models.CharField(default=1, max_length=1000, verbose_name='Haqqında'),
            preserve_default=False,
        ),
    ]
