# Generated by Django 4.0.4 on 2022-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_say',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
