# Generated by Django 4.0.4 on 2022-06-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_time'),
        ('news', '0002_news_time'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='NewsTags',
        ),
    ]
