# Generated by Django 4.0.4 on 2022-05-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_comment_say'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment_say',
        ),
    ]
