# Generated by Django 4.0.5 on 2022-07-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(default=1, max_length=256, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(default=2, max_length=256, verbose_name='Linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(default=1, max_length=256, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.CharField(default=1, max_length=256, verbose_name='İş'),
            preserve_default=False,
        ),
    ]
