# Generated by Django 4.0.4 on 2022-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articletags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCenterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Elanın kateqoriyası')),
            ],
        ),
    ]
