# Generated by Django 4.0.5 on 2022-07-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_facebook_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Twitter'),
        ),
    ]
