# Generated by Django 4.0.4 on 2022-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_careercentercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercentercategory',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Elanın kateqoriyası'),
            preserve_default=False,
        ),
    ]
