# Generated by Django 4.0.4 on 2022-06-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_careercentercategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercenter',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.careercentercategory'),
            preserve_default=False,
        ),
    ]
