# Generated by Django 4.0.4 on 2022-05-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_comments'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('mail', models.CharField(max_length=50, verbose_name='Mail')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('message', models.CharField(max_length=256, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False, verbose_name='is published')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.news')),
            ],
        ),
    ]
