# Generated by Django 4.0.5 on 2022-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad və Soyad')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefon')),
                ('working_status', models.CharField(max_length=150, verbose_name='Hal hazırda işləyirsiniz? (Nə?)')),
                ('education_industry', models.CharField(max_length=150, verbose_name='Təhsil və sənayə təcrübəniz')),
                ('subjects', models.CharField(max_length=150, verbose_name='Hansı mövzuda yaza bilərsiniz?')),
                ('time', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nə qədər vaxtdan bir məzmun təqdim edə bilərsiniz?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('email', models.EmailField(max_length=50, verbose_name='Mail')),
                ('subject', models.CharField(max_length=150, verbose_name='Ne haqda')),
                ('messege', models.CharField(max_length=1000, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
