# Generated by Django 4.0.5 on 2022-06-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subject',
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(default=11, max_length=150, verbose_name='Telefon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ad və Soyad'),
        ),
    ]
