# Generated by Django 4.0.5 on 2022-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nə qədər vaxtdan bir məzmun təqdim edə bilərsiniz?'),
        ),
    ]
