# Generated by Django 4.0.4 on 2022-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='time',
        ),
        migrations.AlterField(
            model_name='author',
            name='working_status',
            field=models.IntegerField(choices=[(1, 'Sektordayam'), (2, 'Tələbəyəm'), (3, 'İşləmirəm')], default=1),
        ),
    ]
