# Generated by Django 4.0.5 on 2022-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_author_subject_author_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='messege',
        ),
        migrations.AddField(
            model_name='author',
            name='working_status',
            field=models.CharField(default=1, max_length=150, verbose_name='Hal hazırda işləyirsiniz? (Nə?)'),
            preserve_default=False,
        ),
    ]
