# Generated by Django 4.0.4 on 2022-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_author_time_alter_author_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='time',
            field=models.CharField(choices=[('1', 'Həftədə 1-2 məqalə'), ('2', 'Həftədə 3-4 məqalə'), ('3', 'Ayda 1-2 məqalə')], default=1, max_length=150, verbose_name='Nə qədər vaxtdan bir məzmun təqdim edə bilərsiniz?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='working_status',
            field=models.IntegerField(max_length=150, verbose_name='Hal hazırda işləyirsiniz? (Nə?)'),
        ),
    ]
