# Generated by Django 4.0.4 on 2022-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_author_time_alter_author_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='time',
            field=models.CharField(max_length=150, verbose_name='Nə qədər vaxtdan bir məzmun təqdim edə bilərsiniz?'),
        ),
    ]
