# Generated by Django 4.0.5 on 2022-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_author_messege_author_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='education_industry',
            field=models.CharField(default=1, max_length=150, verbose_name='Təhsil və sənayə təcrübəniz'),
            preserve_default=False,
        ),
    ]
