# Generated by Django 4.0.4 on 2022-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_author_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='working_status',
            field=models.CharField(max_length=150, verbose_name='Hal hazırda işləyirsiniz? (Nə?)'),
        ),
    ]
