# Generated by Django 4.0.5 on 2022-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_author_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='time',
            field=models.CharField(default=1, max_length=150, verbose_name='Nə qədər vaxtdan bir məzmun təqdim edə bilərsiniz?'),
            preserve_default=False,
        ),
    ]
