# Generated by Django 4.0.5 on 2022-07-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_author_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
