# Generated by Django 4.0.5 on 2022-07-01 19:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descrtiption2',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='descrtiption3',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='descrtiption4',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='descrtiption5',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='descrtiption6',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil'),
        ),
    ]
