# Generated by Django 4.0.5 on 2022-07-23 19:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='descrtiption',
            field=tinymce.models.HTMLField(max_length=10000, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption2',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Məzmun2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption3',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Məzmun3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption4',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Məzmun4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption5',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Məzmun5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption6',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Məzmun6'),
        ),
    ]
