# Generated by Django 4.0.5 on 2022-07-13 09:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descrtiption_block',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun blok'),
        ),
    ]
