# Generated by Django 4.0.4 on 2022-06-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='Neçə dəqiqəlik məqalə'),
        ),
    ]
