# Generated by Django 4.0.5 on 2022-07-01 19:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_descrtiption2_article_descrtiption3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='descrtiption',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption2',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption3',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption4',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption5',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descrtiption6',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Məzmun6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_images', verbose_name='Şekil6'),
        ),
    ]
