# Generated by Django 4.0.4 on 2022-06-28 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articletags'),
        ('article', '0003_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articletags'),
        ),
    ]
