# Generated by Django 4.0.5 on 2022-07-02 22:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_descrtiption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='descrtiption',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='Məzmun'),
        ),
    ]
